version: '3.3'

services:
  db:
    container_name: school_db
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 4DQYa9K63Rz
      MYSQL_DATABASE: schooldb
      MYSQL_USER: schoolu
      MYSQL_PASSWORD: password
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
        - school-net

volumes:
  db-data: { }

networks:
  school-net:
    driver: bridge
